name: Update generated nerdfont header

on:
  push:
      tags:
      - '*'

jobs:

  GenerateHeader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run
      run: go run ./generator/GenerateNerdFontsHeader.go -url="https://www.nerdfonts.com/cheat-sheet" -output="../include/NerdFont.h"
