name: Update Vcpkg Repository

on:
  workflow_dispatch:

jobs:
  update-vcpkg-repository:
    runs-on: ubuntu-latest
    name: Update vcpkg repository
    steps:
      - uses: actions/checkout@v3
      
      - name: Update vcpkg repository
        uses: WesleyDucharme/action-update-vcpkg-repository@v0.3
        with:
          remote-vcpkg-repository: 'git@github.com:WesleyDucharme/vcpkg-repository.git'
